# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 02:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session_Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Account_session', models.CharField(max_length=50)),
                ('User', models.CharField(max_length=100)),
                ('Session_expiry', models.DateTimeField(default=django.utils.timezone.now)),
                ('Last_logged_in', models.DateTimeField(default=django.utils.timezone.now)),
                ('Date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
