# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 02:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Globe_Mobile_Admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMS_Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_code', models.CharField(max_length=50)),
                ('app_sms', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=200)),
                ('shortcode', models.IntegerField(max_length=5)),
                ('xdn_type', models.CharField(max_length=50)),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
