# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 03:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Globe_Mobile_Admin', '0002_sms_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session_table',
            name='Account_session',
            field=models.CharField(max_length=50, verbose_name='Account session'),
        ),
        migrations.AlterField(
            model_name='session_table',
            name='Date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date created'),
        ),
        migrations.AlterField(
            model_name='session_table',
            name='Last_logged_in',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last logged in'),
        ),
        migrations.AlterField(
            model_name='session_table',
            name='Session_expiry',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Session expiry'),
        ),
        migrations.AlterField(
            model_name='session_table',
            name='User',
            field=models.CharField(max_length=100, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='sms_message',
            name='app_code',
            field=models.CharField(max_length=50, verbose_name='App code'),
        ),
        migrations.AlterField(
            model_name='sms_message',
            name='app_sms',
            field=models.CharField(max_length=20, verbose_name='App sms message'),
        ),
        migrations.AlterField(
            model_name='sms_message',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date created'),
        ),
        migrations.AlterField(
            model_name='sms_message',
            name='date_modified',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date modified'),
        ),
        migrations.AlterField(
            model_name='sms_message',
            name='message',
            field=models.CharField(max_length=200, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='sms_message',
            name='shortcode',
            field=models.IntegerField(max_length=5, verbose_name='Shortcode'),
        ),
        migrations.AlterField(
            model_name='sms_message',
            name='xdn_type',
            field=models.CharField(max_length=50, verbose_name='Xdn usage type'),
        ),
    ]
