# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 04:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Globe_Mobile_Admin', '0003_auto_20160524_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Account', models.CharField(max_length=50)),
                ('app_code', models.CharField(max_length=20, verbose_name='App code')),
                ('id_token', models.CharField(max_length=50, verbose_name='Identity token')),
                ('fran_net', models.CharField(max_length=10, verbose_name='Franchise network')),
                ('fran_type', models.CharField(max_length=10, verbose_name='Franchise type')),
                ('date_join', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date joined')),
            ],
        ),
        migrations.AlterField(
            model_name='session_table',
            name='Last_logged_in',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last logged in'),
        ),
        migrations.AlterField(
            model_name='session_table',
            name='Session_expiry',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 23, 4, 7, 20, 350517, tzinfo=utc), verbose_name='Session expiry'),
        ),
        migrations.AlterField(
            model_name='session_table',
            name='User',
            field=models.CharField(max_length=50, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='sms_message',
            name='date_modified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date modified'),
        ),
        migrations.AlterField(
            model_name='sms_message',
            name='shortcode',
            field=models.IntegerField(verbose_name='Shortcode'),
        ),
    ]
