# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 04:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Globe_Mobile_Admin', '0004_auto_20160524_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Account_session', models.CharField(max_length=50, verbose_name='Account session')),
                ('User', models.CharField(max_length=50, verbose_name='User')),
                ('Session_expiry', models.DateTimeField(default=datetime.datetime(2016, 7, 23, 4, 41, 30, 385528, tzinfo=utc), verbose_name='Session expiry')),
                ('Last_logged_in', models.DateTimeField(blank=True, null=True, verbose_name='Last logged in')),
                ('Date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date created')),
            ],
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ver_token', models.CharField(max_length=50, verbose_name='Verification token')),
                ('ver', models.CharField(max_length=10, verbose_name='Verification')),
                ('valid', models.DateTimeField(blank=True, null=True, verbose_name='Valid until')),
                ('Payload', models.CharField(max_length=100)),
                ('last_mod', models.DateTimeField(blank=True, null=True, verbose_name='Last Modified')),
            ],
        ),
        migrations.DeleteModel(
            name='Session_Table',
        ),
    ]
