# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 05:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Globe_Mobile_Admin', '0006_auto_20160524_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='Session_expiry',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 23, 5, 40, 29, 334966, tzinfo=utc), verbose_name='Session expiry'),
        ),
        migrations.AlterField(
            model_name='verification',
            name='Payload',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='verification',
            name='last_mod',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 24, 5, 40, 29, 350732, tzinfo=utc), verbose_name='Last Modified'),
        ),
        migrations.AlterField(
            model_name='verification',
            name='valid',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 24, 5, 50, 29, 350732, tzinfo=utc), verbose_name='Valid until'),
        ),
    ]
