# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 07:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Globe_Mobile_Admin', '0009_auto_20160524_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='Account',
        ),
        migrations.RemoveField(
            model_name='verification',
            name='Payload',
        ),
        migrations.AddField(
            model_name='account',
            name='account',
            field=models.CharField(default='', max_length=50, verbose_name='Account'),
        ),
        migrations.AddField(
            model_name='verification',
            name='payload',
            field=models.CharField(default='', max_length=200, verbose_name='Payload'),
        ),
        migrations.AlterField(
            model_name='session',
            name='Session_expiry',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 25, 7, 32, 55, 484577, tzinfo=utc), verbose_name='Session expiry'),
        ),
        migrations.AlterField(
            model_name='verification',
            name='last_mod',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last Modified'),
        ),
        migrations.AlterField(
            model_name='verification',
            name='valid',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 26, 7, 42, 55, 500203, tzinfo=utc), verbose_name='Valid until'),
        ),
    ]
