# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 07:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Globe_Mobile_Admin', '0011_auto_20160526_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account',
            field=models.CharField(max_length=50, verbose_name='Account'),
        ),
        migrations.AlterField(
            model_name='session',
            name='Session_expiry',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 25, 7, 45, 47, 696886, tzinfo=utc), verbose_name='Session expiry'),
        ),
        migrations.AlterField(
            model_name='verification',
            name='payload',
            field=models.CharField(max_length=200, verbose_name='Payload'),
        ),
        migrations.AlterField(
            model_name='verification',
            name='valid',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 26, 7, 55, 47, 696886, tzinfo=utc), verbose_name='Valid until'),
        ),
    ]
