# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 07:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Globe_Mobile_Admin', '0012_auto_20160526_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='Session_expiry',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 25, 7, 51, 25, 80810, tzinfo=utc), verbose_name='Session expiry'),
        ),
        migrations.AlterField(
            model_name='verification',
            name='valid',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 26, 8, 1, 25, 96437, tzinfo=utc), verbose_name='Valid until'),
        ),
    ]
